CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID   INT PRIMARY KEY AUTO_INCREMENT,
  DEPARTMENT_NAME VARCHAR(30) NOT NULL,
  LOCATION_ID     INT
);
CREATE TABLE JOBS (
  JOB_ID     INT PRIMARY KEY,
  JOB_TITLE  VARCHAR(35) NOT NULL,
  MIN_SALARY INT,
  MAX_SALARY INT
);
CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID    INT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) NOT NULL,
  EMAIL          VARCHAR(25) NOT NULL,
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      DATE,
  JOB_ID         INT         NOT NULL,
  SALARY         DECIMAL(8, 2),
  COMMISSION_PCT DECIMAL(2, 2),
  MANAGER_ID     INT,
  DEPARTMENT_ID  INT
)
CREATE TABLE LOCATIONS (
  LOCATION_ID    INT PRIMARY KEY AUTO_INCREMENT,
  STREET_ADRESS  VARCHAR(40),
  POSTAL_CODE    VARCHAR(12),
  CITY           VARCHAR(30) NOT NULL ,
  STATE_PROVINCE VARCHAR(25)
);

ALTER TABLE employees ADD FOREIGN KEY (JOB_ID) REFERENCES jobs (JOB_ID);
ALTER TABLE employees ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments (DEPARTMENT_ID);
ALTER TABLE employees ADD FOREIGN KEY (MANAGER_ID) REFERENCES employees (EMPLOYEE_ID);
ALTER TABLE departments ADD FOREIGN KEY (LOCATION_ID) REFERENCES locations (LOCATION_ID);

INSERT INTO departments VALUES (1, 'Administration', 1700);
INSERT INTO locations VALUES (1700, 'strada', '1232', 'Bucuresti', 'Bucuresti');
INSERT INTO jobs VALUES (1, 'President', 20000, 40000);
INSERT INTO employees VALUES (1, 'Steven', 'King', 'SKING', '512.123.4567', now(), 1, 2400, NULL, NULL, 1);

ALTER TABLE employees DROP FOREIGN KEY employees_ibfk_1;
ALTER TABLE zth_16.employees DROP FOREIGN KEY employees_ibfk_1;
ALTER TABLE jobs MODIFY JOB_ID VARCHAR(10);






